-- MySQL Script generated by MySQL Workbench
-- Mon Sep  8 09:44:28 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_negocio
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_negocio` ;

-- -----------------------------------------------------
-- Schema db_negocio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_negocio` ;
SHOW WARNINGS;
USE `db_negocio` ;

-- -----------------------------------------------------
-- Table ``
-- -----------------------------------------------------
DROP TABLE IF EXISTS `` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `` (
)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CLIENTE` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `CLIENTE` (
  `id_CLIENTE` INT NOT NULL,
  `NOMBRE` VARCHAR(45) NULL,
  `DIRECCION` VARCHAR(45) NULL,
  `TELEFONO` VARCHAR(15) NULL,
  PRIMARY KEY (`id_CLIENTE`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_CLIENTE_UNIQUE` ON `CLIENTE` (`id_CLIENTE` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `FACTURA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FACTURA` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `FACTURA` (
  `id_FACTURA` INT NOT NULL,
  `FECHA` DATE NULL,
  `CLIENTE_id_CLIENTE` INT NOT NULL,
  PRIMARY KEY (`id_FACTURA`, `CLIENTE_id_CLIENTE`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PRODUCTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PRODUCTO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PRODUCTO` (
  `id_PRODUCTO` INT NOT NULL,
  PRIMARY KEY (`id_PRODUCTO`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `VENTA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VENTA` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `VENTA` (
  `id_VENTA` INT NOT NULL,
  `id_FACTURA` INT NOT NULL,
  `PRODUCTO_id_PRODUCTO` INT NOT NULL,
  `CANTIDAD` INT NULL,
  PRIMARY KEY (`id_VENTA`, `id_FACTURA`, `PRODUCTO_id_PRODUCTO`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `table1` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `table1` (
)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
